from PyQt5 import QtCore, QtGui, QtWidgets ,  QtPrintSupport
import random
# from PyQt5.QtWidgets import QTextEdit, QApplication, QMessageBox, QMainWindow, QPushButton
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 481, 461))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setStyleSheet("background-color: rgb(0, 107, 157);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 10, 451, 411))
        self.frame.setStyleSheet("background-color: rgb(55, 172, 204);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 40, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(390, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_2.setObjectName("label_2")
        self.num_1 = QtWidgets.QSpinBox(self.frame)
        self.num_1.setGeometry(QtCore.QRect(30, 45, 71, 51))
        self.num_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_1.setObjectName("num_1")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(4, 10, 431, 20))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(171, 110, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(391, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_5.setObjectName("label_5")
        self.num_2 = QtWidgets.QSpinBox(self.frame)
        self.num_2.setGeometry(QtCore.QRect(31, 115, 71, 51))
        self.num_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_2.setObjectName("num_2")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(171, 180, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(392, 260, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(391, 190, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_8.setObjectName("label_8")
        self.num_3 = QtWidgets.QSpinBox(self.frame)
        self.num_3.setGeometry(QtCore.QRect(30, 180, 71, 51))
        self.num_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_3.setObjectName("num_3")
        self.num_4 = QtWidgets.QSpinBox(self.frame)
        self.num_4.setGeometry(QtCore.QRect(31, 252, 71, 51))
        self.num_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_4.setObjectName("num_4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(172, 250, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(173, 320, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_10.setObjectName("label_10")
        self.num_5 = QtWidgets.QSpinBox(self.frame)
        self.num_5.setGeometry(QtCore.QRect(32, 322, 71, 51))
        self.num_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_5.setObjectName("num_5")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(393, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 451, 411))
        self.frame_2.setStyleSheet("background-color: rgb(248, 221, 16);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(170, 40, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(390, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_13.setObjectName("label_13")
        self.num_6 = QtWidgets.QSpinBox(self.frame_2)
        self.num_6.setGeometry(QtCore.QRect(30, 45, 71, 51))
        self.num_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_6.setObjectName("num_6")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(4, 10, 431, 20))
        self.label_14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(171, 110, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(391, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_16.setObjectName("label_16")
        self.num_7 = QtWidgets.QSpinBox(self.frame_2)
        self.num_7.setGeometry(QtCore.QRect(31, 115, 71, 51))
        self.num_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_7.setObjectName("num_7")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(171, 180, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(392, 260, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(391, 190, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_19.setObjectName("label_19")
        self.num_8 = QtWidgets.QSpinBox(self.frame_2)
        self.num_8.setGeometry(QtCore.QRect(30, 180, 71, 51))
        self.num_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_8.setObjectName("num_8")
        self.num_9 = QtWidgets.QSpinBox(self.frame_2)
        self.num_9.setGeometry(QtCore.QRect(31, 252, 71, 51))
        self.num_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_9.setObjectName("num_9")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(172, 250, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(173, 320, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_21.setObjectName("label_21")
        self.num_10 = QtWidgets.QSpinBox(self.frame_2)
        self.num_10.setGeometry(QtCore.QRect(32, 322, 71, 51))
        self.num_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_10.setObjectName("num_10")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(393, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setGeometry(QtCore.QRect(10, 9, 451, 411))
        self.frame_3.setStyleSheet("background-color: rgb(0, 0, 97);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(170, 40, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(390, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_24.setObjectName("label_24")
        self.num_11 = QtWidgets.QSpinBox(self.frame_3)
        self.num_11.setGeometry(QtCore.QRect(30, 45, 71, 51))
        self.num_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_11.setObjectName("num_11")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(4, 10, 431, 20))
        self.label_25.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(171, 110, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(391, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_27.setObjectName("label_27")
        self.num_12 = QtWidgets.QSpinBox(self.frame_3)
        self.num_12.setGeometry(QtCore.QRect(31, 115, 71, 51))
        self.num_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_12.setObjectName("num_12")
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(171, 180, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(392, 260, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_3)
        self.label_30.setGeometry(QtCore.QRect(391, 190, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_30.setObjectName("label_30")
        self.num_13 = QtWidgets.QSpinBox(self.frame_3)
        self.num_13.setGeometry(QtCore.QRect(30, 180, 71, 51))
        self.num_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_13.setObjectName("num_13")
        self.num_14 = QtWidgets.QSpinBox(self.frame_3)
        self.num_14.setGeometry(QtCore.QRect(31, 252, 71, 51))
        self.num_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_14.setObjectName("num_14")
        self.label_31 = QtWidgets.QLabel(self.frame_3)
        self.label_31.setGeometry(QtCore.QRect(172, 250, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_3)
        self.label_32.setGeometry(QtCore.QRect(173, 320, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_32.setObjectName("label_32")
        self.num_15 = QtWidgets.QSpinBox(self.frame_3)
        self.num_15.setGeometry(QtCore.QRect(32, 322, 71, 51))
        self.num_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_15.setObjectName("num_15")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(393, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_33.setObjectName("label_33")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_4 = QtWidgets.QFrame(self.tab_4)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 451, 411))
        self.frame_4.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_34 = QtWidgets.QLabel(self.frame_4)
        self.label_34.setGeometry(QtCore.QRect(170, 40, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_4)
        self.label_35.setGeometry(QtCore.QRect(390, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_35.setObjectName("label_35")
        self.num_16 = QtWidgets.QSpinBox(self.frame_4)
        self.num_16.setGeometry(QtCore.QRect(30, 45, 71, 51))
        self.num_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_16.setObjectName("num_16")
        self.label_36 = QtWidgets.QLabel(self.frame_4)
        self.label_36.setGeometry(QtCore.QRect(4, 10, 431, 20))
        self.label_36.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame_4)
        self.label_37.setGeometry(QtCore.QRect(171, 110, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_4)
        self.label_38.setGeometry(QtCore.QRect(391, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_38.setObjectName("label_38")
        self.num_17 = QtWidgets.QSpinBox(self.frame_4)
        self.num_17.setGeometry(QtCore.QRect(31, 115, 71, 51))
        self.num_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_17.setObjectName("num_17")
        self.label_39 = QtWidgets.QLabel(self.frame_4)
        self.label_39.setGeometry(QtCore.QRect(171, 180, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_4)
        self.label_40.setGeometry(QtCore.QRect(392, 260, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_4)
        self.label_41.setGeometry(QtCore.QRect(391, 190, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_41.setObjectName("label_41")
        self.num_18 = QtWidgets.QSpinBox(self.frame_4)
        self.num_18.setGeometry(QtCore.QRect(30, 180, 71, 51))
        self.num_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_18.setObjectName("num_18")
        self.num_19 = QtWidgets.QSpinBox(self.frame_4)
        self.num_19.setGeometry(QtCore.QRect(31, 252, 71, 51))
        self.num_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_19.setObjectName("num_19")
        self.label_42 = QtWidgets.QLabel(self.frame_4)
        self.label_42.setGeometry(QtCore.QRect(172, 250, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_4)
        self.label_43.setGeometry(QtCore.QRect(173, 320, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color: rgb(31, 216, 222);")
        self.label_43.setObjectName("label_43")
        self.num_20 = QtWidgets.QSpinBox(self.frame_4)
        self.num_20.setGeometry(QtCore.QRect(32, 322, 71, 51))
        self.num_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_20.setObjectName("num_20")
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        self.label_44.setGeometry(QtCore.QRect(393, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.label_44.setObjectName("label_44")
        self.tabWidget.addTab(self.tab_4, "")
        self.btn_total = QtWidgets.QPushButton(self.centralwidget)
        self.btn_total.setGeometry(QtCore.QRect(720, 384, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_total.setFont(font)
        self.btn_total.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_total.setStyleSheet("border_radius:15 px;\n"
"\n"
"background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btn_total.setObjectName("btn_total")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(490, 0, 421, 311))
        self.textEdit.setObjectName("textEdit")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(490, 383, 111, 71))
        self.btn_total.clicked.connect(self.total)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_clear.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_clear.clicked.connect(self.Clear)
        self.btn_Print = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Print.setGeometry(QtCore.QRect(605, 384, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Print.setFont(font)
        self.btn_Print.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_Print.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"color: rgb(255, 255, 255);")
        self.btn_Print.setObjectName("btn_Print")
        self.btn_Print.clicked.connect(self.Print)
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(490, 320, 141, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(249, 249, 27);")
        self.label_45.setObjectName("label_45")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(640, 330, 271, 41))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "      آش"))
        self.label_2.setText(_translate("MainWindow", " 1"))
        self.label_3.setText(_translate("MainWindow", " تعداد  |                      غذاها                    |      چند عدد"))
        self.label_4.setText(_translate("MainWindow", "   حلیم شیر"))
        self.label_5.setText(_translate("MainWindow", " 2"))
        self.label_6.setText(_translate("MainWindow", "   حلیم عدس"))
        self.label_7.setText(_translate("MainWindow", " 4"))
        self.label_8.setText(_translate("MainWindow", " 3"))
        self.label_9.setText(_translate("MainWindow", "      نیمرو"))
        self.label_10.setText(_translate("MainWindow", " سوسیس تخم مرغ"))
        self.label_11.setText(_translate("MainWindow", " 5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "صبحانه"))
        self.label_12.setText(_translate("MainWindow", "  چلو کباب"))
        self.label_13.setText(_translate("MainWindow", " 6"))
        self.label_14.setText(_translate("MainWindow", " تعداد  |                      غذاها                    |      چند عدد"))
        self.label_15.setText(_translate("MainWindow", "    چلو جوجه"))
        self.label_16.setText(_translate("MainWindow", " 7"))
        self.label_17.setText(_translate("MainWindow", "   بریانی (اصفهانی)"))
        self.label_18.setText(_translate("MainWindow", " 9"))
        self.label_19.setText(_translate("MainWindow", " 8"))
        self.label_20.setText(_translate("MainWindow", "      دیزی"))
        self.label_21.setText(_translate("MainWindow", "    کباب شیشلیگ"))
        self.label_22.setText(_translate("MainWindow", " 10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "ناهار"))
        self.label_23.setText(_translate("MainWindow", " خوراک کباب"))
        self.label_24.setText(_translate("MainWindow", " 11"))
        self.label_25.setText(_translate("MainWindow", " تعداد  |                      غذاها                    |      چند عدد"))
        self.label_26.setText(_translate("MainWindow", "  خوراک جوجه"))
        self.label_27.setText(_translate("MainWindow", " 12"))
        self.label_28.setText(_translate("MainWindow", "     غذای محلی"))
        self.label_29.setText(_translate("MainWindow", " 14"))
        self.label_30.setText(_translate("MainWindow", " 13"))
        self.label_31.setText(_translate("MainWindow", "          قیمه"))
        self.label_32.setText(_translate("MainWindow", "     قورمه سبزی"))
        self.label_33.setText(_translate("MainWindow", " 15"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "شام "))
        self.label_34.setText(_translate("MainWindow", " نوشابه خانواده"))
        self.label_35.setText(_translate("MainWindow", " 16"))
        self.label_36.setText(_translate("MainWindow", " تعداد  |                      غذاها                    |      چند عدد"))
        self.label_37.setText(_translate("MainWindow", "   نوشابه قوطی"))
        self.label_38.setText(_translate("MainWindow", " 17"))
        self.label_39.setText(_translate("MainWindow", "    دوغ محلی"))
        self.label_40.setText(_translate("MainWindow", " 19"))
        self.label_41.setText(_translate("MainWindow", " 18"))
        self.label_42.setText(_translate("MainWindow", "  خورشت ماست"))
        self.label_43.setText(_translate("MainWindow", "   سالاد های فصل"))
        self.label_44.setText(_translate("MainWindow", " 20"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "دسر و نوشیدنی"))
        self.btn_total.setText(_translate("MainWindow", "عملیات"))
        self.btn_clear.setText(_translate("MainWindow", "پاک"))
        self.btn_Print.setText(_translate("MainWindow", "پرینت"))
        self.label_45.setText(_translate("MainWindow", ": نام خانوادگی"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

        self.customer_queue = 1

    def Clear(self):
        self.textEdit.clear()
        self.lineEdit.clear()
        self.num_1.setValue(0)
        self.num_2.setValue(0)
        self.num_3.setValue(0)
        self.num_4.setValue(0)
        self.num_5.setValue(0)
        self.num_6.setValue(0)
        self.num_7.setValue(0)
        self.num_8.setValue(0)
        self.num_9.setValue(0)
        self.num_10.setValue(0)
        self.num_11.setValue(0)
        self.num_12.setValue(0)
        self.num_13.setValue(0)
        self.num_14.setValue(0)
        self.num_15.setValue(0)
        self.num_16.setValue(0)
        self.num_17.setValue(0)
        self.num_18.setValue(0)
        self.num_19.setValue(0)
        self.num_20.setValue(0)
    def Print(self):
        document = QtGui.QTextDocument()
        document.setPlainText(self.textEdit.toPlainText())
        printer = QtPrintSupport.QPrinter()
        printer.setPrinterName("Printer Name")  # Set your printer name or use default
        dialog = QtPrintSupport.QPrintDialog(printer)
        if dialog.exec_() == QtPrintSupport.QDialog.Accepted:
            document.print_(printer)
    #         Save

    def total(self):
            import messagebox
            import os
            for _ in range(1):  # به عنوان مثال، 5 مشتری
                    self.ticket_number = self.customer_queue
                    self.customer_queue += 1
            self.name=self.lineEdit.text()
            # messagebox.showinfo("ذخیره نام مشتری",format(self.name))
            Spain_v_1 = self.num_1.value()
            Spain_v_2 = self.num_2.value()
            Spain_v_3 = self.num_3.value()
            Spain_v_4 = self.num_4.value()
            Spain_v_5 = self.num_5.value()
            Spain_v_6 = self.num_6.value()
            Spain_v_7 = self.num_7.value()
            Spain_v_8 = self.num_8.value()
            Spain_v_9 = self.num_9.value()
            Spain_v_10 = self.num_10.value()
            Spain_v_11 = self.num_11.value()
            Spain_v_12 = self.num_12.value()
            Spain_v_13 = self.num_13.value()
            Spain_v_14 = self.num_14.value()
            Spain_v_15 = self.num_15.value()
            Spain_v_16 = self.num_16.value()
            Spain_v_17 = self.num_17.value()
            Spain_v_18 = self.num_18.value()
            Spain_v_19 = self.num_19.value()
            Spain_v_20 = self.num_20.value()
            # step 2
            Ash_f = Spain_v_1 * 3000
            Healim_f = Spain_v_2 * 15000
            HealimAdas_f = Spain_v_3 * 9000
            Nimro_f = Spain_v_4 * 9000
            Sosis_f = Spain_v_5 * 9000
            Kabab_f = Spain_v_6 * 9000
            Jojeh_f = Spain_v_7 * 9000
            Berian_f = Spain_v_8 * 9000
            Dizy_f = Spain_v_9 * 9000
            Kabab_six_f = Spain_v_10 * 9000
            Khorak_kabab_f = Spain_v_11 * 9000
            Khorak_Jojeh_f = Spain_v_12 * 9000
            Meahealy_f = Spain_v_13 * 9000
            GHeaymeh_f = Spain_v_14 * 9000
            Ghormeh_f = Spain_v_15 * 9000
            Nosh_Khan_f = Spain_v_16 * 9000
            Nosh_Ghoty_f = Spain_v_17 * 9000
            Dogh_f = Spain_v_18 * 9000
            KhoreshMast_f = Spain_v_19 * 9000
            Salad_f = Spain_v_20 * 9000
            #     step 3
            total_sum = Ash_f + Healim_f + HealimAdas_f + HealimAdas_f + Nimro_f + Sosis_f + Kabab_f + Jojeh_f + Berian_f + Dizy_f + Kabab_six_f \
                        + Khorak_kabab_f + Khorak_Jojeh_f + Meahealy_f + GHeaymeh_f + Ghormeh_f + Nosh_Khan_f + Nosh_Ghoty_f + Dogh_f + KhoreshMast_f + Salad_f
            self.textEdit.insertPlainText(f"  ______________________نام رستوران______________________   \n\n")
            self.textEdit.insertPlainText(f"  __________________خوش آمدید به رستوران_________________   \n\n")
            self.textEdit.insertPlainText(f"  شماره رستوران :093658543353\n")
            self.textEdit.insertPlainText(f"  پذیرش :آقای فلان\n")
            self.textEdit.insertPlainText(f"  ______________________منوی عذاها______________________   \n\n")
            a='ريال'
            if Ash_f or Healim_f or HealimAdas_f or Nimro_f or Sosis_f != 0:
                self.textEdit.insertPlainText(f"....................................... صبحانه ..................  تعداد \n")
            if Ash_f != 0:
                self.textEdit.insertPlainText(f"   آش:                                   {Ash_f}  {a}            {self.num_1.value()} \n")
            if Healim_f != 0:
                self.textEdit.insertPlainText(f"  حلیم:                                  {Healim_f}  {a}          {self.num_2.value()} \n")
            if HealimAdas_f != 0:
                self.textEdit.insertPlainText(f"  حلیم عدس:                          {HealimAdas_f}  {a}           {self.num_3.value()} \n")
            if Nimro_f != 0:
                self.textEdit.insertPlainText(f"  نیمرو:                                   {Nimro_f}  {a}           {self.num_4.value()} \n")
            if Sosis_f != 0:
                self.textEdit.insertPlainText(f"  سوسیس تخم مرغ:                {Sosis_f}  {a}           {self.num_5.value()} \n")

            if Kabab_f or Jojeh_f or Berian_f or Dizy_f or Kabab_six_f != 0:
                self.textEdit.insertPlainText(f"....................................... ناهار ....................  تعداد \n")
            if Kabab_f != 0:
                self.textEdit.insertPlainText(f"  چلو کباب :                              {Kabab_f}  {a}          {self.num_6.value()} \n")
            if Jojeh_f != 0:
                self.textEdit.insertPlainText(f"  چلو جوجه :                             {Jojeh_f}  {a}          {self.num_7.value()} \n")
            if Berian_f != 0:
                self.textEdit.insertPlainText(f"  بریانی (اصفهانی) :                  {Berian_f}  {a}          {self.num_8.value()} \n")
            if Dizy_f != 0:
                self.textEdit.insertPlainText(f"  دیزی :                                   {Dizy_f}  {a}          {self.num_9.value()} \n")
            if Kabab_six_f != 0:
                self.textEdit.insertPlainText(f"  کباب شیشلیگ :                    {Kabab_six_f}  {a}          {self.num_10.value()} \n")

            if Khorak_kabab_f or Khorak_Jojeh_f or Meahealy_f or GHeaymeh_f or Ghormeh_f != 0:
                self.textEdit.insertPlainText(f"....................................... شام ....................  تعداد \n")
            if Khorak_kabab_f != 0:
                self.textEdit.insertPlainText(f"    خوراک کباب :                        {Khorak_kabab_f}  {a}          {self.num_11.value()} \n")
            if Khorak_Jojeh_f != 0:
                self.textEdit.insertPlainText(f"  خوراک جوجه :                         {Khorak_Jojeh_f}  {a}          {self.num_12.value()} \n")
            if Meahealy_f != 0:
                self.textEdit.insertPlainText(f"  غذای محلی :                         {Meahealy_f}  {a}          {self.num_13.value()} \n")
            if GHeaymeh_f != 0:
                self.textEdit.insertPlainText(f"  خورشت فیمه :                       {GHeaymeh_f}  {a}          {self.num_14.value()} \n")
            if Ghormeh_f != 0:
                self.textEdit.insertPlainText(f"  خورشت قورمه :                      {Ghormeh_f}  {a}          {self.num_15.value()} \n")

            if Nosh_Khan_f or Nosh_Ghoty_f or Dogh_f or KhoreshMast_f or Salad_f != 0:
                self.textEdit.insertPlainText(f"......................... دسر و نوشیدنی .................  تعداد \n")
            if Nosh_Khan_f != 0:
                self.textEdit.insertPlainText(f"  نوشابه خانواده :                     {Nosh_Khan_f}  {a}          {self.num_16.value()} \n")
            if Nosh_Ghoty_f != 0:
                self.textEdit.insertPlainText(f"  نوشابه قوطی :                      {Nosh_Ghoty_f}  {a}          {self.num_17.value()} \n")
            if Dogh_f != 0:
                self.textEdit.insertPlainText(f"  دوغ محلی :                           {Dogh_f}  {a}          {self.num_18.value()} \n")
            if KhoreshMast_f != 0:
                self.textEdit.insertPlainText(f"  خورشت ماست :                    {KhoreshMast_f}  {a}          {self.num_19.value()} \n")
            if Salad_f != 0:
                self.textEdit.insertPlainText(f"  سالاد فصل :                          {Salad_f}  {a}          {self.num_20.value()} \n")
            self.textEdit.insertPlainText(f"................................................................................................\n\n")
            self.textEdit.insertPlainText(f"       جمع کل :                          {total_sum} ریال\n\n")
            self.textEdit.insertPlainText(f"                  نام مشتری :   {self.name}         شماره نوبت:{self.ticket_number}\n")
            self.textEdit.insertPlainText(f"__________________________________________________________\n")
            # Save data
            self.dil='Menu Resturant'
            i = self.textEdit.toPlainText()
            os.makedirs('bills', exist_ok=True)
            with open(f'bills/{self.dil}.txt', 'a') as file:
                file.write(i)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
